name: PyPI

on: [push, pull_request, release]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [ '3.7', '3.8' ]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install the development and release requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r dev_requirements.pip
        pip install wheel twine
    - name: Run tests
      run: nosetests
    - name: Cleanup build and dist folders
      run: rm -rf build dist pyxform.egg-info
    - name: Prepare sdist and bdist_wheel distributions
      run: python setup.py sdist bdist_wheel
    - name: Publish release to PyPI with twine
      if: github.event_name == 'release' && github.event.action == 'created' && matrix.python == '3.8'
      run: twine upload dist/pyxform-*-py3-none-any.whl dist/pyxform-*.tar.gz
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
